[package]
name = "autogui_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
hex = "0.4.3"
image = "0.24.7"
thiserror = "1.0.47"
